name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *' # every day at 01:30

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Configure setting as stale and closing
        uses: actions/stale@v8 # documentation: https://github.com/actions/stale
        with:
          repo-token: ${{ github.token }}
          stale-pr-message: 'This PR is stale. Please comment or update code within 7 days or it will be automatically closed.'
          # stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale' # excluding marking issues as stale
          exempt-pr-labels: "feature branch,security,don't merge yet"
          close-pr-message: 'This PR is being automatically closed because it is stale.'
          delete-branch: false
          days-before-stale: 60
          days-before-close: 7
          remove-stale-when-updated: true
          stale-pr-label: 'Stale'
          exempt-draft-pr: true