name: Destroy staging environment

on:
  pull_request: 
    types: [ unlabeled ]

jobs:
  build:
    if: github.event.label.name == 'AWS staging'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
